version: '3'

services:
  nginx:
    container_name: symfony_nginx
    image: nginx:stable
    restart: unless-stopped
    tty: true
    ports:
      - "9080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
    working_dir: /var/www/html
    networks:
      - symfony-net

  php:
    container_name: symfony_php
    image: symfony_php
    build:
      context: .
      dockerfile: .docker/php/php.Dockerfile
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    ports:
      - "9081:9081"
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - symfony-net

  db:
      container_name: symfony_db
      image: postgres:latest
      command: -p 9082
      restart: always
      tty: true
      ports:
          - "9082:9082"
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: symfony
      volumes:
          - ./.docker/postgresql/data:/var/lib/postgresql/data
      networks:
          - symfony-net

networks:
  symfony-net:
    driver: "bridge"
